learning_log/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('learning_logs.urls')),
]

learning_logs/urls.py
from django.urls import path

from . import views


app_name = 'learning_logs'
urlpatterns = [
    # Main page
    path('', views.index, name='index'),
    path('topics/', views.topics, name='topics'),
    path('topics/<int:topic_id>/', views.topic, name='topic'),
]

learning_logs/models.py
from django.db import models

# Create your models here.


class Topic(models.Model):
    """Topic what user learns"""
    text = models.CharField(max_length=200)
    date_added = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.text


class Entry(models.Model):
    """Info for specific Topic"""
    topic = models.ForeignKey(Topic, on_delete=models.CASCADE)
    text = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name_plural = 'entries'

    def __str__(self):
        if len(self.text) > 50:
            return f"{self.text[:50]}..."
        else:
            return f"{self.text[:50]}"

learning_logs/views.py
from django.shortcuts import render
from .models import Topic, Entry


def index(request):
    """Main page"""
    return render(request, 'learning_logs/index.html')


def topics(request):
    """Show all topics."""
    all_topics = Topic.objects.order_by('date_added')
    context = {'all_topics': all_topics}
    return render(request, 'learning_logs/topics.html', context)


def topic(request, topic_id):
    """Show single topic per page"""
    single_topic = Topic.objects.get(id=topic_id)
    entries = single_topic.entry_set.order_by('-date_added')
    context = {'single_topic': single_topic, 'entries': entries}
    return render(request, 'learning_logs/topic.html', context)

learning_logs/templates/learning_logs/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% if title %}
        <title>{{ title }}</title>
    {% else %}
        <title>Learning Logs Project</title>
    {% endif %}
</head>
<body>

    <p>
        <a href="{% url 'learning_logs:index' %}">Learning Log</a> -
        <a href="{% url 'learning_logs:topics' %}">Topics</a>
    </p>

    {% block content %} {% endblock content %}

</body>
</html>

learning_logs/templates/learning_logs/index.html
{% extends 'learning_logs/base.html' %}

{% block content %}

    <p>Learning logs.</p>
    <p>Learning logs helps you to track some informations.</p>

{% endblock content %}

learning_logs/templates/learning_logs/topic.html
{% extends 'learning_logs/base.html' %}

{% block content %}

    <p>This is single page for {{ single_topic }}</p>

    <p>Entries:</p>
    <ul>
        {% for entry in entries %}
            <li>{{ entry.date_added }}</li>
            <li>{{ entry.text|linebreaks }}</li>
        {% empty %}
            <li>There's no entry for this topic yet.</li>
        {% endfor %}
    </ul>

{% endblock content %}

learning_logs/templates/learning_logs/topics.html
{% extends 'learning_logs/base.html' %}

{% block content %}

    <p>All topics</p>
    <ul>
        {% for topic in all_topics %}
            <li><a href="{% url 'learning_logs:topic' topic.id %}">{{ topic }}</a></li>
        {% empty %}
            <li>No topics have been added yet.</li>
        {% endfor %}
    </ul>

{% endblock content %}